trigger:
  - 'None'

pool:
  name: 'Self-hosted'

steps:
  - script: |
      echo "This is a dummy file" > dummy.txt
      echo "This is an updated dummy file" > dummy.txt
    displayName: 'Create Dummy File'

  - task: Bash@3
    env:
      AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)
    inputs:
      targetType: 'inline'
      script: |
        echo "Running az login with System.AccessToken"
        az extension add --name azure-devops

        sourceBranch="$(Build.SourceBranch)"
        sourceBranch=${sourceBranch#refs/heads/}
        
        targetBranch="master"

        timestamp=$(date +'%Y-%m-%d %H:%M:%S')
        echo "Source Branch: $sourceBranch"
        echo "Target Branch: $targetBranch"
        echo "Current Timestamp: $timestamp"

        existingPR=$(az repos pr list --organization https://dev.azure.com/kamilsaiyed/ \
                                      --project "KamilSaiyed" \
                                      --repository "KamilSaiyed" \
                                      --source-branch "$sourceBranch" \
                                      --target-branch "$targetBranch" \
                                      --status "active" \
                                      --query '[0].pullRequestId' \
                                      --output tsv)
        if [[ -n "$existingPR" ]]; then
          echo "Updating existing pull request with ID: $existingPR"
          az repos pr update --organization https://dev.azure.com/kamilsaiyed/ \
                             --id "$existingPR" \
                             --title "Updated PR for $sourceBranch at $timestamp" \
                             --description "This PR was updated by the pipeline at $timestamp."
        else
          echo "No active PR found. Creating a new one."
          az repos pr create --organization https://dev.azure.com/kamilsaiyed/ \
                             --project "KamilSaiyed" \
                             --repository "KamilSaiyed" \
                             --source-branch "$sourceBranch" \
                             --target-branch "$targetBranch" \
                             --title "Automated PR for $sourceBranch at $timestamp" \
                             --description "This PR was created by the pipeline at $timestamp."
        fi
    displayName: 'Update or Create Pull Request'
