trigger:
  - master

pool:
  name: 'Self-hosted'  # Ensure this is the correct name of your self-hosted agent pool

steps:
  - script: |
      echo "This is a dummy file" > dummy.txt
    displayName: 'Create Dummy File'

  - task: AzureCLI@2
    inputs:
      azureSubscription: 'Azure subscription 1 (fabd0ca9-f841-4a2e-860b-4ec1267dd6a9)'  # Replace with the correct service connection name
      scriptType: 'ps'  # Use 'ps' for PowerShell
      scriptLocation: 'inlineScript'
      inlineScript: |
        # Obtain the Microsoft Entra (Azure AD) access token
        $accessToken = az account get-access-token --resource 499b84ac-1321-427f-aa17-267ca6975798 --query accessToken --output tsv
        
        # Use the token to authenticate with Azure DevOps API or CLI
        az devops configure --defaults organization=https://dev.azure.com/kamilsaiyed/ project=KamilSaiyed
        
        # Call Azure DevOps CLI to create a pull request using the access token
        az repos pr create --organization https://dev.azure.com/kamilsaiyed/ --project KamilSaiyed --repository KamilSaiyed --source-branch kamilsaiyed/OneBranch_Test --target-branch master --title "Automated Pull Request for Dummy File" --description "This PR was created by the pipeline." --detect true --access-token $accessToken
    displayName: 'Create Pull Request'
