trigger:
  - master

pool:
  name: 'Self-hosted'

variables:
  - group: ServicePrincipalSecrets  # Reference the secure variable group

steps:
  - script: |
      echo "This is a dummy file" > dummy.txt
    displayName: 'Create Dummy File'

  - task: AzureCLI@2
    inputs:
      azureSubscription: 'Azure subscription 1 (fabd0ca9-f841-4a2e-860b-4ec1267dd6a9)'  # Ensure the correct service connection
      scriptType: 'ps'
      scriptLocation: 'inlineScript'
      inlineScript: |
        # Login using the service principal credentials stored in secure variables
        az login --service-principal -u $(APP_ID) --password $(CLIENT_SECRET) --tenant $(TENANT_ID)
        
        # Configure Azure DevOps CLI defaults
        az devops configure --defaults organization=https://dev.azure.com/kamilsaiyed/ project=KamilSaiyed

        # Create a pull request in Azure DevOps
        az repos pr create --organization https://dev.azure.com/kamilsaiyed/ --project KamilSaiyed --repository KamilSaiyed --source-branch kamilsaiyed/OneBranch_Test --target-branch master --title "Automated Pull Request for Dummy File" --description "This PR was created by the pipeline."
    displayName: 'Create Pull Request'
