trigger:
  - master

pool:
  vmImage: 'windows-latest'

steps:
  - script: |
      echo "This is a dummy file" > dummy.txt
    displayName: 'Create Dummy File'

  - task: AzureCLI@2
    inputs:
      azureSubscription: 'Azure subscription 1 (fabd0ca9-f841-4a2e-860b-4ec1267dd6a9)'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        # Create pull request using Azure CLI
        az repos pr create \
          --repository $(Build.Repository.Name) \
          --source-branch kamilsaiyed/OneBranch_Test \
          --target-branch development \
          --title "Automated Pull Request for Dummy File" \
          --description "This PR was created by the pipeline."
    displayName: 'Create Pull Request'
