trigger:
  - 'None'

pool:
  name: 'Self-hosted'

variables:
  - group: ServicePrincipalSecrets

steps:
  - script: |
      echo "This is a dummy file" > dummy.txt
    displayName: 'Create Dummy File'
  - task: AzureCLI@2
    env:
      # APP_ID: $(APP_ID)
      # CLIENT_SECRET: $(CLIENT_SECRET)
      # TENANT_ID: $(TENANT_ID)
      AZURE_DEVOPS_EXT_PAT: $(PAT)
    inputs:
      azureSubscription: 'serviceconnection_01'
      scriptType: 'ps'
      scriptLocation: 'inlineScript'
      inlineScript: |
        
        az extension add --name azure-devops
        
        $sourceBranch = "$(Build.SourceBranch)"
        $sourceBranch = $sourceBranch -replace '^refs/heads/', ''
        
        $targetBranch = "master"

        echo "Source Branch: $sourceBranch"
        echo "Target Branch: $targetBranch"

        az repos pr create --organization https://dev.azure.com/kamilsaiyed/ --project KamilSaiyed --repository KamilSaiyed --source-branch $sourceBranch --target-branch $targetBranch --title "Automated PR for $sourceBranch" --description "This PR was created by the pipeline."
    displayName: 'Create Pull Request'
