trigger:
  - master

pool:
  name: 'Self-hosted'

variables:
  - group: ServicePrincipalSecrets

steps:
  - script: |
      echo "This is a dummy file" > dummy.txt
    displayName: 'Create Dummy File'

  - task: AzureCLI@2
    env:
      APP_ID: $(APP_ID)
      CLIENT_SECRET: $(CLIENT_SECRET)
      TENANT_ID: $(TENANT_ID)
      AZURE_DEVOPS_EXT_PAT: $(PAT)
    inputs:
      azureSubscription: 'serviceconnection_01'
      scriptType: 'ps'
      scriptLocation: 'inlineScript'
      inlineScript: |
        # Login using the service principal credentials
        az login --service-principal -u $(APP_ID) --password $(CLIENT_SECRET) --tenant $(TENANT_ID)

        # Set the correct subscription explicitly
        az account set --subscription fabd0ca9-f841-4a2e-860b-4ec1267dd6a9
        
        # Install the Azure DevOps CLI extension
        az extension add --name azure-devops
        
        # Configure Azure DevOps CLI defaults
        az devops configure --defaults organization=https://dev.azure.com/kamilsaiyed/ project=KamilSaiyed
        
        # Generate a unique title for the pull request using timestamp
        PR_TITLE="Automated PR for Dummy File - $(date +'%Y-%m-%d %H:%M:%S')"
        
        # Create a pull request in Azure DevOps with a unique title
        az repos pr create --organization https://dev.azure.com/kamilsaiyed/ --project KamilSaiyed --repository KamilSaiyed --source-branch kamilsaiyed/OneBranch_Test --target-branch master --title "$PR_TITLE" --description "This PR was created by the pipeline."
    displayName: 'Create Pull Request'
